version: 2
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t desbonnm/nada:$TAG .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push desbonnm/nada:$TAG
